### ISSUE TITLE
How to add filter to the environment?

### ISSUE THREAD

**Issue by xorinox** [BUADCP2013/CS473-EX_CMS#14]
I could not figure out how to add the filter to the environment. post_display_tz_filter is my branch.

environment.filters['datetimezone'] = filters.Filters.DateTimeZone   BUT where to put this line?

jinja2.exceptions.TemplateAssertionError

TemplateAssertionError: no filter named 'datetimeformat'
Traceback (most recent call last)

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

    File "C:\server\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "C:\git\CS473-EX_CMS\letterbucket\__init__.py", line 71, in index_page

    truncate=should_truncate)

    File "C:\server\Python27\lib\site-packages\flask\templating.py", line 127, in render_template

    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),

    File "C:\server\Python27\lib\site-packages\jinja2\environment.py", line 830, in get_or_select_template

    return self.get_template(template_name_or_list, parent, globals)

    File "C:\server\Python27\lib\site-packages\jinja2\environment.py", line 791, in get_template

    return self._load_template(name, self.make_globals(globals))

    File "C:\server\Python27\lib\site-packages\jinja2\environment.py", line 765, in _load_template

    template = self.loader.load(self, name, globals)

    File "C:\server\Python27\lib\site-packages\jinja2\loaders.py", line 125, in load

    code = environment.compile(source, name, filename)

    File "C:\server\Python27\lib\site-packages\jinja2\environment.py", line 554, in compile

    self.handle_exception(exc_info, source_hint=source)

    File "C:\server\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "C:\git\CS473-EX_CMS\letterbucket\templates\index.html", line 11, in template

    <th>{{ post.pub_date|datetimeformat('US/Eastern') }}</th>

    TemplateAssertionError: no filter named 'datetimeformat'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by DirtNap** [comment]
I'll look at this in the morning
